name = "BenchmarkProfiles"
uuid = "ecbce9bc-3e5e-569d-9e29-55181f61f8d0"
version = "0.3.3"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
DataFrames = "^0.22.7"
NaNMath = "0.3"
Requires = "1"
julia = "^1.3.0"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
test = ["Plots", "Test", "UnicodePlots"]
